# SPDX-FileCopyrightText: None
#
# SPDX-License-Identifier: CC0-1.0

description = "SorairoLakeã®å€‹äººãƒ–ãƒ­ã‚°"
mainSections = ["posts"]

[dateFormat]
published = "2006å¹´1æœˆ2æ—¥"
lastUpdated = "2006å¹´1æœˆ2æ—¥ 15:04 MST"

[sidebar]
emoji = "ğŸ§"
subtitle = "æ›¸ããŸã„ã¨æ€ã£ãŸã“ã¨ã‚’é©å½“ã«æ›¸ãã¾ã™"

[sidebar.avatar]
src = "images/profile.png"

[footer]
since = 2021

[article]
math = true
toc = true

[article.license]
enabled = true
default = "ã“ã®è¨˜äº‹ã¯[CC BY 4.0](https://creativecommons.org/licenses/by/4.0/deed.ja)ã®ä¸‹ã§ãƒ©ã‚¤ã‚»ãƒ³ã‚¹ã•ã‚Œã¦ã„ã¾ã™"

[[widgets.homepage]]
type = "search"

[[widgets.homepage]]
type = "archives"

[[widgets.homepage]]
type = "categories"

[[widgets.homepage]]
type = "tag-cloud"

[[widgets.page]]
type = "toc"

[opengraph.twitter]
site = "sorairolake"
card = "summary"

[defaultImage.opengraph]
enabled = true
src = "images/profile.png"
local = true
